# Superuser that has SSH login permitted
admin_user: ccdcadmin

# Skip all tasks and reupload the SSH public key only
rotate_pubkey: false

# Disable password auth and root login on SSH (true), or skip (false)
disable_root: true
disable_password: true


# Install Python on all systems
bootstrap: false

# Enable logging high-volume events in auditd
auditd_highvolumeevents: false

############################
###   ADVANCED OPTIONS   ###
############################

# Blacklist for SUID/SGID entries to be removed
# Cherrypicked from gtfobins.github.io
uid_sgid_system_blacklist:
  - /usr/bin/arp
  - /bin/ash
  - /usr/bin/awk
  - /bin/bash
  - /bin/cat
  - /usr/bin/chmod
  - /usr/bin/chroot
  - /usr/bin/chown
  - /bin/cp
  - /usr/bin/curl
  - /usr/bin/cut
  - /usr/bin/date
  - /usr/bin/dd
  - /usr/local/bin/docker
  - /usr/bin/file
  - /usr/bin/find
  - /usr/bin/grep
  - /usr/bin/head
  - /usr/bin/hexdump
  - /usr/bin/ip
  - /usr/bin/jq
  - /usr/bin/ld.so
  - /usr/local/bin/kubectl
  - /usr/bin/less
  - /bin/mv
  - /usr/bin/sed
  - /usr/bin/ss
  - /usr/bin/ssh-agent
  - /usr/bin/ssh-keygen
  - /usr/bin/ssh-keyscan
  - /usr/bin/strings
  - /usr/bin/tail
  - /usr/bin/sysctl
  - /usr/bin/systemctl
  - /usr/bin/tee
  - /usr/bin/uniq
  - /usr/bin/vim
  - /usr/bin/wget
  - /usr/bin/xxd
  - /bin/zsh